version: 2

project_name: kubectl-sbom

before:
  hooks:
    - go mod tidy

builds:
  - id: kubectl-sbom
    main: ./cmd/kubectl-sbom
    binary: kubectl-sbom
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: kubectl-sbom
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt

changelog:
  disable: true
